build(deps): fix minimum colorama version (#1403)
After this PR https://github.com/copier-org/copier/pull/1379   method `just_fix_windows_console` is used instead of `init` So is need install `colorama>=0.4.6` because this method is add in commit https://github.com/tartley/colorama/commit/5f1794d1aac9f2f5be4893bcc8ba8a061b9aeb08
otherwise raise error
AttributeError: module 'colorama' has no attribute 'just_fix_windows_console'